FROM node:20-alpine

WORKDIR /frontend

COPY package*.json ./
RUN npm install

COPY . .  

# Expose the port for the frontend
EXPOSE 3000

CMD ["npm", "run", "dev"]  # This command will start the frontend application
