services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT:-8080}:8080"  
    env_file:
      - backend/.env  
    depends_on:
      redis:  
        condition: service_started
    networks:
      - my_network  

  redis:
    image: redis:7.0-alpine  
    container_name: redis
    ports:
      - "6379:6379"  
    networks:
      - my_network  

networks:
  my_network:
    driver: bridge  
